kicad2itead 1.2
I've changed the script for BASH output cleanup and compressing in the -PTH file for cuts (it was skipped in the initial 1.1 release)

diff --git a/kicad2itead b/kicad2itead
--- a/kicad2itead
+++ b/kicad2itead
@@ -18,8 +18,10 @@
 # Updates by Chris Bergeron (Inhibit) 2019
 #    v1.0: Downloaded release from doragasu on github
 #    v1.1: Changed the script to accomodate the new KiCad filenames it also
-#    now copies the files to a subdirectory "backup/" prior to overwriting them.
-
+#          now copies the files to a subdirectory "backup/" prior to overwriting
+#          them.
+#    v1.2: Cleanup to compress in the cut layer (-PTH) and for nicer BASH
+#          output.
 
 # Color definitions for the command line
 RED='\033[1;31m'
@@ -27,7 +29,7 @@ GREEN='\033[1;32m'
 NEUTRAL='\033[0m'
 
 # Original Gerber files, as KiCad names them
-ORG_FILES="-F_Cu.gbr -B_Cu.gbr -F_Mask.gbr -B_Mask.gbr -F_SilkS.gbr -B_SilkS.gbr -Edge_Cuts.gbr .drl -NPTH.drl"
+ORG_FILES="-F_Cu.gbr -B_Cu.gbr -F_Mask.gbr -B_Mask.gbr -F_SilkS.gbr -B_SilkS.gbr -Edge_Cuts.gbr -PTH.drl -NPTH.drl"
 # Destination Gerber files, as required by iTead Studio
 DST_FILES=".GTL .GBL .GTS .GBS .GTO .GBO .GKO .TXT -NPTH.TXT"
 # Description of each Gerber file
@@ -45,15 +47,20 @@ ZIP_FILES=""
 # ZIP_FILES global variable is updated with the list of the renamed files.
 RenameGerber()
 {
-	mkdir backup
+	# Check if we have a backup directory
+	if [ ! -d "backup" ]
+	then
+		mkdir backup
+	fi
+
 	if [ -w "$1""$2" ]
 	then
 		cp "$1""$2" backup/
 		mv "$1""$2" "$1""$3"
-		echo -e "$GREEN""$4: $1$3""$NEUTRAL"
+		echo "$GREEN""$4: $1$3""$NEUTRAL"
 		ZIP_FILES=`echo "$ZIP_FILES $1$3"`
 	else
-		echo -e "$RED""$4 NOT FOUND!""$NEUTRAL"
+		echo "$RED""$4 NOT FOUND!""$NEUTRAL"
 	fi
 }
 
@@ -68,7 +75,7 @@ fi
 for ORG_FILE in $ORG_FILES
 do
 	DST_FILE=`echo $DST_FILES | cut -d' ' -f$IDX`
-	DESCRIPT=`echo -e $DESCRIPTS | cut -f$IDX`
+	DESCRIPT=`echo  $DESCRIPTS | cut -f$IDX`
 	RenameGerber "$1" $ORG_FILE $DST_FILE "$DESCRIPT"
 	IDX=`expr $IDX + 1`
 done
@@ -76,11 +83,11 @@ done
 # ZIP resulting files, or error if there are no files to zip.
 if [ -n "$ZIP_FILES" ]
 then
-	echo -e "\nCREATING ARCHIVE $1.zip:"
+	echo "\nCREATING ARCHIVE $1.zip:"
 	zip -9 "$1".zip $ZIP_FILES
-	echo -e "$GREEN"DONE!"$NEUTRAL"
+	echo "$GREEN"DONE!"$NEUTRAL"
 else
-	>&2 echo -e "\n$RED"NO FILES FOUND, ARCHIVE NOT CREATED"$NEUTRAL"
+	>&2 echo "\n$RED"NO FILES FOUND, ARCHIVE NOT CREATED"$NEUTRAL"
 	exit 2
 fi
 
